import styles from "@/styles/Home.module.css";
import Head from "next/head";
import PokemonContainer from "../components/PokemonContainer";
import PokemonBlog from "../components/PokemonBlog";

export default function Home() {
  return (
    <>
      <Head>
        <title>Pokemon</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <PokemonContainer />
        <PokemonBlog />
      </main>
    </>
  );
}
